"""Independent frozen arithmetic, units and mixture limits for Phase 3."""

import math

import pytest

from ald_twin.gas_properties import (
    H2O_MOLAR_MASS,
    N2_MOLAR_MASS,
    nitrogen_viscosity,
    water_nitrogen_diffusivity,
    water_viscosity,
    wilke_binary_viscosity,
)
from ald_twin.units import sccm_to_molar_flow


@pytest.mark.parametrize(
    "temperature,diffusion,nitrogen,water,mixture",
    [
        (373.15, 0.01670, 2.0620e-5, 1.3222e-5, 2.03995e-5),
        (423.15, 0.02118, 2.2465e-5, 1.4959e-5, 2.22471e-5),
        (473.15, 0.02608, 2.4212e-5, 1.6732e-5, 2.40010e-5),
    ],
)
def test_reproduces_freeze_with_only_printed_rounding_tolerance(
    temperature, diffusion, nitrogen, water, mixture
):
    # These values were frozen before implementation, not generated by this test.
    actual_nitrogen = nitrogen_viscosity(temperature)
    actual_water = water_viscosity(temperature)
    assert water_nitrogen_diffusivity(temperature, 200) == pytest.approx(diffusion, abs=5e-6, rel=0)
    assert actual_nitrogen == pytest.approx(nitrogen, abs=5e-10, rel=0)
    assert actual_water == pytest.approx(water, abs=5e-10, rel=0)
    actual_mixture = wilke_binary_viscosity(
        16 / 516, actual_water, actual_nitrogen, H2O_MOLAR_MASS, N2_MOLAR_MASS
    )
    assert actual_mixture == pytest.approx(mixture, abs=5e-11, rel=0)


def test_diffusion_uses_local_pressure_and_full_temperature_dependence():
    reference = water_nitrogen_diffusivity(423.15, 200)
    assert water_nitrogen_diffusivity(423.15, 735) == pytest.approx(reference * 200 / 735, rel=1e-14)
    # Collision integrals vary with T: a pure T**1.5 scaling is incomplete.
    hot = water_nitrogen_diffusivity(473.15, 200)
    assert hot > reference * (473.15 / 423.15)**1.5


def test_wilke_independent_book_example_and_species_order():
    # Poling Example 9-5: methane/n-butane, 293 K; its intermediate values
    # were rounded, hence the 0.03 micropoise arithmetic tolerance.
    result = wilke_binary_viscosity(0.697, 109.4e-7, 72.74e-7, 0.016043, 0.058123)
    assert result == pytest.approx(92.26e-7, abs=0.03e-7, rel=0)
    reverse = wilke_binary_viscosity(0.303, 72.74e-7, 109.4e-7, 0.058123, 0.016043)
    assert result == pytest.approx(reverse, rel=1e-14)


@pytest.mark.parametrize("fraction,expected", [(0, 3e-5), (1, 1e-5)])
def test_wilke_pure_component_limits(fraction, expected):
    assert wilke_binary_viscosity(fraction, 1e-5, 3e-5, 0.018, 0.028) == expected


@pytest.mark.parametrize("invalid", [0, -1, math.inf, math.nan, None, True])
def test_properties_reject_invalid_temperature_and_pressure(invalid):
    for function in (nitrogen_viscosity, water_viscosity):
        with pytest.raises(ValueError):
            function(invalid)
    with pytest.raises(ValueError):
        water_nitrogen_diffusivity(423.15, invalid)


@pytest.mark.parametrize("temperature", [1, 1e6])
def test_no_silent_collision_integral_extrapolation(temperature):
    for function in (nitrogen_viscosity, water_viscosity):
        with pytest.raises(ValueError, match="T\\*"):
            function(temperature)
    with pytest.raises(ValueError, match="T\\*"):
        water_nitrogen_diffusivity(temperature, 200)


def test_wilke_rejects_invalid_composition_and_properties():
    for fraction in (-0.1, 1.1, math.nan):
        with pytest.raises(ValueError):
            wilke_binary_viscosity(fraction, 1e-5, 2e-5, 0.018, 0.028)
    for values in [(0, 2e-5, 0.018, 0.028), (1e-5, 2e-5, 0.018, None)]:
        with pytest.raises(ValueError):
            wilke_binary_viscosity(0.1, *values)


def test_declared_standard_flows_reproduce_frozen_molar_and_mass_flows():
    for flow, mass, molar_reference, mass_reference in [
        (500, N2_MOLAR_MASS, 3.71792e-4, 1.04152e-5),
        (11, 0.12350, 8.17942e-6, 1.01016e-6),
        (16, H2O_MOLAR_MASS, 1.18973e-5, 2.14334e-7),
    ]:
        molar = sccm_to_molar_flow(flow, 273.15, 101325)
        assert molar == pytest.approx(molar_reference, rel=5e-6)
        assert molar * mass == pytest.approx(mass_reference, rel=5e-6)
