"""Generate original quiet tones for a clean source export, using no recordings."""

import argparse
import json
import math
from pathlib import Path
import struct
import wave


def make_sounds(output):
    output = Path(output)
    output.mkdir(parents=True, exist_ok=False)
    sample_rate = 24000
    cues = {"click": (720, .045), "crystal": (1040, .16), "complete": (780, .28)}
    for name, (frequency, duration) in cues.items():
        samples = bytearray()
        count = round(sample_rate * duration)
        for index in range(count):
            # A smooth envelope starts and ends at zero, preventing sharp clicks.
            envelope = math.sin(math.pi * index / (count - 1)) ** 2
            value = .15 * envelope * math.sin(2 * math.pi * frequency * index / sample_rate)
            samples.extend(struct.pack("<h", round(32767 * value)))
        with wave.open(str(output / f"{name}.wav"), "wb") as sound:
            sound.setparams((1, 2, sample_rate, count, "NONE", "not compressed"))
            sound.writeframes(samples)
    provenance = {"source": "Original sine tones generated by packaging/make_public_sounds.py",
                  "external_recordings": False, "sample_rate_hz": sample_rate,
                  "cues": {name: {"frequency_hz": frequency, "duration_s": duration}
                           for name, (frequency, duration) in cues.items()}}
    (output / "provenance.json").write_text(json.dumps(provenance, indent=2) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True, help="New audio directory")
    make_sounds(parser.parse_args().output)
