"""generate original quiet tones for a clean source export, using no recordings."""

import argparse
import json
import math
from pathlib import Path
import struct
import wave

# 16-bit mono audio at 24 kHz
SAMPLE_RATE = 24000
CHANNELS = 1
SAMPLE_WIDTH_BYTES = 2
FULL_SCALE = 32767

# peak loudness as a fraction of full scale
AMPLITUDE = .15

# each cue as (frequency in Hz, duration in s)
CUES = {"click": (720, .045), "crystal": (1040, .16), "complete": (780, .28)}


def tone_samples(frequency, count):
    """return one faded sine tone as little-endian 16-bit samples."""
    samples = bytearray()
    for index in range(count):
        # fade both ends to zero to avoid sharp clicks.
        envelope = math.sin(math.pi * index / (count - 1)) ** 2
        value = AMPLITUDE * envelope * math.sin(2 * math.pi * frequency * index / SAMPLE_RATE)
        samples.extend(struct.pack("<h", round(FULL_SCALE * value)))
    return samples


def make_sounds(output):
    """write each cue as a wav file plus a provenance.json into a new folder."""
    output = Path(output)
    output.mkdir(parents=True, exist_ok=False)
    for name, (frequency, duration) in CUES.items():
        count = round(SAMPLE_RATE * duration)
        samples = tone_samples(frequency, count)
        with wave.open(str(output / f"{name}.wav"), "wb") as sound:
            sound.setparams((CHANNELS, SAMPLE_WIDTH_BYTES, SAMPLE_RATE, count, "NONE", "not compressed"))
            sound.writeframes(samples)

    # record how the tones were made
    cues = {}
    for name, (frequency, duration) in CUES.items():
        cues[name] = {"frequency_hz": frequency, "duration_s": duration}
    provenance = {"source": "Original sine tones generated by packaging/make_public_sounds.py",
                  "external_recordings": False, "sample_rate_hz": SAMPLE_RATE, "cues": cues}
    (output / "provenance.json").write_text(json.dumps(provenance, indent=2) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True, help="New audio directory")
    make_sounds(parser.parse_args().output)
